### ISSUE TITLE
TypeError: this.errorCallback is not a function

### ISSUE THREAD

**Issue by 111qqz** [jprichardson/potter-wordpress#2]
Hi, I get some problems here. When I run potter-wordpress , it can fetch some  articles successfully,and then it will get a "TypeError: this.errorCallback is not a function" error. 
```
/home/coder/.nvm/versions/node/v12.2.0/lib/node_modules/pottercms-wordpress/node_modules/wp2md/lib/wp2md.js:92
                  if (err) this.errorCallback(err);
                                ^

TypeError: this.errorCallback is not a function
    at /home/coder/.nvm/versions/node/v12.2.0/lib/node_modules/pottercms-wordpress/node_modules/wp2md/lib/wp2md.js:92:33
    at ChildProcess.<anonymous> (/home/coder/.nvm/versions/node/v12.2.0/lib/node_modules/pottercms-wordpress/node_modules/pdc/pandoc.js:35:14)
    at ChildProcess.emit (events.js:196:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)

```

**Comment by jprichardson** [comment]
Hi, this project is dead and has not been updated in 6 years.
